#!/usr/bin/env python3
"""Regenerate Sources/keymonster/Editor/EmojiNamesTable.swift from emoji-data.

Slack's composer exposes an emoji to accessibility as an image whose only
identifying attribute is its description: Slack's short name, "tada emoji".
Putting the character back needs Slack's name table, which is the emoji-data
project (maintained by a Slack engineer, and what Slack itself ships).

Usage: scripts/emoji-names.py [path-to-emoji.json]
Downloads the current emoji.json when no path is given.
"""
import json
import sys
import urllib.request

URL = "https://raw.githubusercontent.com/iamcal/emoji-data/master/emoji.json"
OUT = "Sources/keymonster/Editor/EmojiNamesTable.swift"


def predicted_variation(base, tones):
    """The skin-toned sequence `EmojiNames` derives itself: the first tone goes
    after the first code point (displacing a variation selector), a second one
    goes at the end. Variations the rule gets wrong are listed explicitly."""
    parts = base.split("-")
    rest = parts[1:]
    if rest and rest[0] == "FE0F":
        rest = rest[1:]
    if len(tones) == 1:
        return "-".join([parts[0], tones[0]] + rest)
    return "-".join([parts[0], tones[0]] + rest + [tones[1]])


def main():
    if len(sys.argv) > 1:
        with open(sys.argv[1], "rb") as handle:
            data = json.load(handle)
    else:
        with urllib.request.urlopen(URL) as response:
            data = json.load(response)

    lines = []
    exceptions = 0
    for entry in sorted(data, key=lambda e: e["short_name"]):
        lines.append(f"{','.join(entry['short_names'])} {entry['unified']}")
        for key, variation in (entry.get("skin_variations") or {}).items():
            if predicted_variation(entry["unified"], key.split("-")) != variation["unified"]:
                lines.append(f"{entry['short_name']}|{key} {variation['unified']}")
                exceptions += 1

    with open(OUT, "w", encoding="utf-8") as out:
        out.write("// Generated by scripts/emoji-names.py from emoji-data; do not edit.\n")
        out.write(f"// {len(data)} emoji, {exceptions} explicit skin-tone variations.\n")
        out.write("// swiftlint:disable file_length\n\n")
        out.write("// swiftlint:disable:next type_body_length\n")
        out.write("enum EmojiNamesTable {\n")
        out.write("    /// One entry per line: comma-separated short names, a space, the\n")
        out.write("    /// code points joined by hyphens. Lines with `name|tones` are skin-tone\n")
        out.write("    /// variations the insertion rule in `EmojiNames` doesn't predict.\n")
        out.write('    static let contents = """\n')
        out.write("\n".join(lines))
        out.write('\n"""\n}\n')
    print(f"wrote {OUT}: {len(data)} emoji, {exceptions} explicit variations, {len(lines)} lines")


if __name__ == "__main__":
    main()
