import AppKit

/// Polls `NSPasteboard.general.changeCount` and reports new string contents.
///
/// macOS provides no change notification for the pasteboard, so the supported
/// pattern is to poll the monotonic `changeCount` on a timer and only read the
/// contents when it actually changes.
@MainActor
final class ClipboardWatcher {
    private let pasteboard = NSPasteboard.general
    private var lastChangeCount: Int
    private var timer: Timer?
    private let onChange: (String) -> Void

    /// Pasteboard types that, by the nspasteboard.org convention, mark content
    /// we should not record (passwords, transient/auto-generated data).
    private static let skipTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
    ]

    init(onChange: @escaping (String) -> Void) {
        self.onChange = onChange
        self.lastChangeCount = NSPasteboard.general.changeCount
    }

    func start(interval: TimeInterval = 0.4) {
        timer = Timer.scheduledTimer(withTimeInterval: interval, repeats: true) { [weak self] _ in
            // scheduledTimer fires on the main run loop, so we're on the main actor.
            MainActor.assumeIsolated {
                self?.poll()
            }
        }
    }

    func stop() {
        timer?.invalidate()
        timer = nil
    }

    private func poll() {
        let count = pasteboard.changeCount
        guard count != lastChangeCount else { return }
        lastChangeCount = count

        // Respect concealed/transient markers from password managers etc.
        if let types = pasteboard.types,
           types.contains(where: { Self.skipTypes.contains($0.rawValue) }) {
            return
        }

        if let str = pasteboard.string(forType: .string) {
            onChange(str)
        }
    }
}
